#!/bin/bash

NOCONFIRM=""
AURNOCONFIRM=""

prompt_for_sudo() {
    if [[ $(id -u) -ne 0 ]]; then
       SUDO="sudo"
        echo "This action requires root privileges. Do you want to proceed? (y/n)"
        read -r answer
       case "${answer,,}" in
            y|yes)
                if ! sudo -v; then
                    echo "Failed to obtain sudo privileges."
                    exit 1
                fi
                ;;
            *)
                echo "Operation cancelled."
                exit 1
                ;;
        esac
    else
      SUDO=""
    fi
}

TEMP_ARGS=()
for arg in "$@"; do
    case $arg in
        -y)
            NOCONFIRM="--noconfirm"
            AURNOCONFIRM="--noconfirm --answerdiff None --answerclean None --mflags \"--noconfirm\""
            ;;
        *)
            TEMP_ARGS+=("$arg")
            ;;
    esac
done
set -- "${TEMP_ARGS[@]}"

help() {
        cat <<EOF
Usage: pac <command> [options]

Commands:
    update          Update package database
    upgrade         Upgrade all installed packages
    install         Install a new package
    remove          Remove an installed package
    autoremove      Remove unneeded packages
    clean           Clean the package cache
    autoclean       Remove old versions of installed packages
    list-installed  List all installed packages
    search          Search the package database
    show            Show detailed package information
    find            Find a package by binary name
    aur-search      Search in the AUR
    aur-install     Install a package from the AUR

Options:
    -y              Answer yes to all questions
EOF
}

if [[ "$1" == "--help" ]]; then
    help
    exit 0
fi

case "$1" in
    update)
        prompt_for_sudo
        $SUDO pacman -Sy $NOCONFIRM
    ;;
    upgrade)
        prompt_for_sudo
        $SUDO pacman -Syu $NOCONFIRM
    ;;
    install)
        shift
        prompt_for_sudo
        $SUDO pacman -S "$@" $NOCONFIRM
    ;;
    remove)
        shift
        prompt_for_sudo
        $SUDO pacman -R "$@" $NOCONFIRM
    ;;
    autoremove)
        prompt_for_sudo
        $SUDO pacman -Rs $(pacman -Qtdq) $NOCONFIRM
    ;;
    clean)
        prompt_for_sudo
        $SUDO pacman -Scc $NOCONFIRM
    ;;
    autoclean)
        prompt_for_sudo
        $SUDO pacman -Rns $(pacman -Qtdq $NOCONFIRM) $NOCONFIRM
    ;;
    list-installed)
        pacman -Q
    ;;
    search)
        shift
        local pattern=$(echo "$@" | sed 's/\*/.*/g;s/\?/./g')
        pacman -Ss "$pattern"
    ;;
    show)
        shift
        pacman -Si "$@"
    ;;
    find)
        shift
        pacman -F "$@"
    ;;
    aur-search)
        shift
        yay -Ssa "$@"
    ;;
    aur-install)
        shift
        yay -S "$@" $AURNOCONFIRM
    ;;
    *)
        help
        exit 1
esac
